/**
 * Page exports
 *
 * Each page is a lazy-loaded component that corresponds to a route
 */

export { default as AuthCallbackPage } from './AuthCallback'
export { default as BblnICOPage } from './BblnICO'
export { default as ChartDetailPage } from './ChartDetail'
export { default as ChartsPage } from './Charts'
export { default as CoinCreatePage } from './CoinCreate'
export { default as CoinDetailPage } from './CoinDetail'
export { default as CoinLaunchPage } from './CoinLaunch'
export { default as CoinsPage } from './Coins'
export { default as FaucetPage } from './Faucet'
export { default as GamesPage } from './Games'
export { default as HomePage } from './Home'
export { default as HyperscapePage } from './Hyperscape'
export { default as IntelPage } from './Intel'
export { default as ItemDetailPage } from './ItemDetail'
export { default as ItemMintPage } from './ItemMint'
export { default as ItemsPage } from './Items'
export { default as JejuICOPage } from './JejuICO'
export { default as JejuWhitepaperPage } from './JejuWhitepaper'
export { default as LiquidityPage } from './Liquidity'
export { default as MarketDetailPage } from './MarketDetail'
export { default as MarketsPage } from './Markets'
export { default as NamesPage } from './Names'
export { default as NotFoundPage } from './NotFound'
export { default as PerpsPage } from './Perps'
export { default as PerpsDetailPage } from './PerpsDetail'
export { default as PoolsPage } from './Pools'
export { default as PortfolioPage } from './Portfolio'
export { default as PredictionDetailPage } from './PredictionDetail'
export { default as PredictionDetailErrorPage } from './PredictionDetailError'
export { default as PredictionsErrorPage } from './PredictionsError'
export { default as ProfileDetailPage } from './ProfileDetail'
export { default as RewardsPage } from './Rewards'
export { default as SettingsPage } from './Settings'
export { default as SharePnLPage } from './SharePnL'
export { default as ShareReferralPage } from './ShareReferral'
export { default as SwapPage } from './Swap'
export { default as TFMMPage } from './TFMM'
export { default as TrendingGroupPage } from './TrendingGroup'
export { default as TrendingTagPage } from './TrendingTag'
