/**
 * Training infrastructure for GRPO, Psyche, and compute integration.
 */

export {
  createDWSClient,
  type DWSClientConfig,
  type DWSJobStatus,
  DWSTrainingClient,
  getDefaultDWSConfig,
  isDWSAvailable,
  type JudgeResult,
  type RolloutAction,
  type RolloutData,
  type RolloutMetadata,
  type RolloutObservation,
  type RolloutStep,
  type TrainingJobRequest,
  type TrainingJobResult,
  type TrainingJobStatus,
} from './compute'
export {
  type APIServerConfig,
  type Board,
  type Cell,
  type Completion,
  type CompletionResult,
  createFundamentalPredictionEnv,
  createTicTacToeEnv,
  type FundamentalEnvConfig,
  FundamentalPredictionEnv,
  type GameState,
  type GameStep,
  type GameTrajectory,
  type Move,
  type Player,
  type ScoredDataGroup,
  TicTacToeEnv,
  type TrainingItem,
  trajectoryToTrainingFormat,
} from './environments'
export {
  type AtroposState,
  type BatchData,
  createAtroposServer,
  createDistributedGRPOTrainer,
  createGRPOTrainer,
  DistributedGRPOTrainer,
  type EnvConfig as AtroposEnvConfig,
  GRPOTrainer,
  type Message as AtroposMessage,
  type RegisterEnv,
  type Registration,
  type ScoredData,
  startAtroposServer,
  type TrainerStatus,
  type TrainingConfig,
  type TrainingMetrics,
} from './grpo'
export {
  type AgentTrajectory,
  AutocratTrainingClient,
  CrucibleTrainingClient,
  type CrucibleTrainingMetrics,
  createAutocratTrainingClient,
  createCrucibleTrainingClient,
  type ModelDeploymentProposal,
  type TrainingAgentConfig,
  type TrainingEnvironment,
  type TrainingProposal,
  type TrainingRun,
  type TrajectoryMetadata,
  type TrajectoryStep,
} from './integrations'
export {
  type BridgeConfig,
  type BridgedRunState,
  type CheckpointData,
  type ClientInfo,
  type ClientRegistration,
  type CoordinatorConfig,
  type CoordinatorProgress,
  type CoordinatorState,
  CrossChainTrainingBridge,
  createCrossChainBridge,
  createPsycheClient,
  type Model,
  PsycheClient,
  type PsycheConfig,
  type PsycheTrainingMetrics,
  type RewardDistribution,
  type RunMetadata,
  type WitnessProof,
} from './psyche'

export {
  clearRubrics,
  DEFAULT_RUBRIC,
  getAllRubrics,
  getRubric,
  getRubricCount,
  getRubricOrDefault,
  hasRubric,
  type JudgeRubric,
  listRubrics,
  onRubricChange,
  type RubricRegistry,
  registerOrUpdateRubric,
  registerRubric,
  rubricRegistry,
  unregisterRubric,
} from './rubrics'

export {
  AgentRegistrationResponseSchema,
  AtroposStartResponseSchema,
  BatchResponseSchema,
  CompletionResponseSchema,
  DisconnectEnvSchema,
  DWSJobStatusSchema,
  EnvRegistrationResponseSchema,
  HealthResponseSchema,
  InfoResponseSchema,
  JobAllocationsResponseSchema,
  JobIdResponseSchema,
  JobsListResponseSchema,
  JobsListResponseSchemaExternal,
  JudgeResponseSchema,
  JudgeResultSchema,
  MerkleProofResponseSchema,
  MerkleRootResponseSchema,
  MessageSchema,
  ProposalStatusResponseSchema,
  RegisterEnvSchema,
  RegisterResponseSchema,
  RegistrationSchema,
  RunInfoResponseSchema,
  ScoredDataListResponseSchema,
  ScoredDataListSchema,
  ScoredDataSchema,
  StatusResponseSchema,
  TrainingJobStatusSchema,
} from './schemas'
