/**
 * Training infrastructure for GRPO, Psyche, and compute integration.
 */

// App training adapters (for vendor apps)
export {
  type AppTrainingConfig,
  AppTrainingRunner,
  type AppTrajectoryContext,
  type AppTrajectoryStep,
  type CollectOptions,
  createAppTrainingAdapter,
  getDefaultAppTrainingConfig,
  type HuggingFaceExportConfig,
  type LLMCallRecord,
  type TrainingDataAdapter,
  type TrainingLoopConfig,
  type TrainingLoopResult,
  type TrainingResult,
  type Trajectory,
  type TrajectoryStatus,
} from './apps/index.js'
// Benchmark infrastructure
export {
  type A2AMethodParams,
  type A2AResponse,
  // Types
  type AgentAction,
  type BenchmarkComparisonResult,
  type BenchmarkConfig,
  // Classes
  BenchmarkDataGenerator,
  type BenchmarkGameSnapshot,
  type BenchmarkGameState,
  type BenchmarkRunConfig,
  type BuySharesParams,
  type BuySharesResult,
  type CausalEventType,
  type ChatEntry,
  type ClosePositionResult,
  type CreateCommentResult,
  type CreatePostResult,
  type DashboardResult,
  type GroundTruth,
  type GroupChat,
  // Model registry
  getAllModels,
  getBaselineModels,
  getModelById,
  getModelByModelId,
  getModelDisplayName,
  getModelsByProvider,
  getModelsByTier,
  type HiddenNarrativeFact,
  type JoinGroupResult,
  MODEL_REGISTRY,
  type ModelConfig,
  type ModelProvider,
  type ModelTier,
  type OpenPositionResult,
  type PerpetualMarket,
  type PerpMetrics,
  type PortfolioPosition,
  type PortfolioResult,
  type Post,
  type PredictionMarket,
  type PredictionMetrics,
  registerModel,
  type ScheduledCausalEvent,
  SeededRandom,
  type SellSharesResult,
  type SimulatedAgent,
  SimulationA2AInterface,
  type SimulationAgentState,
  type SimulationConfig,
  SimulationEngine,
  type SimulationEngineState,
  type SimulationFeedPost,
  type SimulationGroupChat,
  type SimulationMetrics,
  type SimulationPerpetualMarket,
  type SimulationPredictionMarket,
  type SimulationResult,
  type SimulationSocialMetrics,
  type Tick,
  type TickEvent,
  type TimingMetrics,
  type TrendingTagEntry,
  type VolatilityBucket,
  validateModelId,
} from './benchmark'
export {
  createDWSClient,
  type DWSClientConfig,
  type DWSJobStatus,
  DWSTrainingClient,
  getDefaultDWSConfig,
  isDWSAvailable,
  type JudgeResult,
  type RolloutAction,
  type RolloutData,
  type RolloutMetadata,
  type RolloutObservation,
  type RolloutStep,
  type TrainingJobRequest,
  type TrainingJobResult,
  type TrainingJobStatus,
} from './compute'
export {
  type APIServerConfig,
  type Board,
  type Cell,
  type Completion,
  type CompletionResult,
  createFundamentalPredictionEnv,
  createTicTacToeEnv,
  type FundamentalEnvConfig,
  FundamentalPredictionEnv,
  type GameState,
  type GameStep,
  type GameTrajectory,
  type Move,
  type Player,
  type ScoredDataGroup,
  TicTacToeEnv,
  type TrainingItem,
  trajectoryToTrainingFormat,
} from './environments'
export {
  type AtroposState,
  type BatchData,
  createAtroposServer,
  createDistributedGRPOTrainer,
  createGRPOTrainer,
  DistributedGRPOTrainer,
  type EnvConfig as AtroposEnvConfig,
  GRPOTrainer,
  type Message as AtroposMessage,
  type RegisterEnv,
  type Registration,
  type ScoredData,
  startAtroposServer,
  type TrainerStatus,
  type TrainingConfig,
  type TrainingMetrics,
} from './grpo'
// HuggingFace integration
export {
  type DatasetExportConfig,
  ensureHuggingFaceRepository,
  generateModelCard,
  getHuggingFaceManualUploadInstructions,
  getHuggingFaceToken,
  type ModelUploadConfig,
  requireHuggingFaceToken,
  uploadDirectoryToHuggingFace,
  uploadFileToHuggingFace,
  uploadToHuggingFaceViaCLI,
} from './huggingface'
export {
  type AgentTrajectory,
  AutocratTrainingClient,
  CrucibleTrainingClient,
  type CrucibleTrainingMetrics,
  type CrucibleTrajectoryStep,
  createAutocratTrainingClient,
  createCrucibleTrainingClient,
  type ModelDeploymentProposal,
  type TrainingAgentConfig,
  type TrainingEnvironment,
  type TrainingProposal,
  type TrainingRun,
  type TrajectoryMetadata,
} from './integrations'

// Metrics extraction
export {
  type BehavioralMetrics,
  type BehaviorMetrics,
  getMetricsSummary,
  type InfluenceMetrics,
  type InformationMetrics,
  type MetricsSummary,
  type SocialMetrics,
  type TradingMetrics,
  TrajectoryMetricsExtractor,
  trajectoryMetricsExtractor,
} from './metrics'
export {
  type BridgeConfig,
  type BridgedRunState,
  type CheckpointData,
  type ClientInfo,
  type ClientRegistration,
  type CoordinatorConfig,
  type CoordinatorProgress,
  type CoordinatorState,
  CrossChainTrainingBridge,
  createCrossChainBridge,
  createPsycheClient,
  type Model,
  PsycheClient,
  type PsycheConfig,
  type PsycheTrainingMetrics,
  type RewardDistribution,
  type RunMetadata,
  type WitnessProof,
} from './psyche'
// Recording infrastructure
export {
  // Trajectory recorder types
  type ActiveTrajectory,
  // Instances
  defaultStorage,
  type EndTrajectoryOptions,
  // Window utilities
  generateWindowIds,
  getCurrentWindowId,
  getPreviousWindowId,
  getWindowIdForTimestamp,
  getWindowRange,
  // Classes
  InMemoryTrajectoryStorage,
  isTimestampInWindow,
  isWindowComplete,
  type LLMCallLogRecord,
  type ParsedWindowId,
  parseWindowId,
  type StartTrajectoryOptions,
  type TrajectoryRecord as StoredTrajectoryRecord,
  TrajectoryRecorder,
  type TrajectoryStorage,
  trajectoryRecorder,
  type WindowRange,
} from './recording'
export {
  // Archetype rubrics
  ARCHETYPE_PRIORITY_METRICS,
  ARCHETYPE_RUBRICS,
  ARCHETYPE_RUBRICS_VERSION,
  ASS_KISSER_PRIORITY_METRICS,
  ASS_KISSER_RUBRIC,
  // Crucible security archetypes
  BLUE_TEAM_PRIORITY_METRICS,
  BLUE_TEAM_RUBRIC,
  // Registry functions
  clearRubrics,
  DEFAULT_ARCHETYPE_PRIORITY_METRICS,
  DEFAULT_ARCHETYPE_RUBRIC,
  DEFAULT_RUBRIC,
  DEGEN_PRIORITY_METRICS,
  DEGEN_RUBRIC,
  GOODY_TWOSHOES_PRIORITY_METRICS,
  GOODY_TWOSHOES_RUBRIC,
  getAllArchetypeRubricsHash,
  getAllRubrics,
  getArchetypePriorityMetrics,
  getArchetypeRubric,
  getArchetypeRubricHash,
  getAvailableArchetypes,
  getRubric,
  getRubricCount,
  getRubricOrDefault,
  hasArchetypeRubric,
  hasRubric,
  INFORMATION_TRADER_PRIORITY_METRICS,
  INFORMATION_TRADER_RUBRIC,
  INFOSEC_PRIORITY_METRICS,
  INFOSEC_RUBRIC,
  type JudgeRubric,
  LIAR_PRIORITY_METRICS,
  LIAR_RUBRIC,
  listRubrics,
  onRubricChange,
  PERPS_TRADER_PRIORITY_METRICS,
  PERPS_TRADER_RUBRIC,
  RED_TEAM_PRIORITY_METRICS,
  RED_TEAM_RUBRIC,
  RESEARCHER_PRIORITY_METRICS,
  RESEARCHER_RUBRIC,
  type RubricRegistry,
  registerArchetypeRubrics,
  registerOrUpdateRubric,
  registerRubric,
  rubricRegistry,
  SCAMMER_PRIORITY_METRICS,
  SCAMMER_RUBRIC,
  SOCIAL_BUTTERFLY_PRIORITY_METRICS,
  SOCIAL_BUTTERFLY_RUBRIC,
  SUPER_PREDICTOR_PRIORITY_METRICS,
  SUPER_PREDICTOR_RUBRIC,
  TRADER_PRIORITY_METRICS,
  TRADER_RUBRIC,
  unregisterRubric,
} from './rubrics'
export {
  // Trajectory types and schemas
  type Action,
  ActionSchema,
  AgentRegistrationResponseSchema,
  AtroposStartResponseSchema,
  BatchResponseSchema,
  CompletionResponseSchema,
  DisconnectEnvSchema,
  DWSJobStatusSchema,
  type EnvironmentState,
  EnvironmentStateSchema,
  EnvRegistrationResponseSchema,
  HealthResponseSchema,
  InfoResponseSchema,
  JobAllocationsResponseSchema,
  JobIdResponseSchema,
  JobsListResponseSchema,
  JobsListResponseSchemaExternal,
  JudgeResponseSchema,
  JudgeResultSchema,
  type LLMCall,
  LLMCallSchema,
  MerkleProofResponseSchema,
  MerkleRootResponseSchema,
  MessageSchema,
  ProposalStatusResponseSchema,
  type ProviderAccess,
  ProviderAccessSchema,
  parseTrajectorySteps,
  RegisterEnvSchema,
  RegisterResponseSchema,
  RegistrationSchema,
  type RulerScoreResponse,
  RulerScoreResponseSchema,
  RunInfoResponseSchema,
  ScoredDataListResponseSchema,
  ScoredDataListSchema,
  ScoredDataSchema,
  StatusResponseSchema,
  TrainingJobStatusSchema,
  type TrajectoryData,
  TrajectoryDataSchema,
  type TrajectoryScoreResponse,
  TrajectoryScoreResponseSchema,
  type TrajectoryStep,
  TrajectoryStepSchema,
} from './schemas'
// LLM-as-judge scoring
export {
  type ArchetypeScore,
  ArchetypeScoringService,
  type CachedScore,
  type CacheStats,
  createScoringService,
  type ILLMCallerForScoring,
  type JudgeCacheConfig,
  JudgePromptBuilder,
  type JudgePromptOptions,
  judgePromptBuilder,
  LLMJudgeCache,
  llmJudgeCache,
  type ScoringOptions,
  type ScoringTrajectoryRecord,
  scoreValidator,
  type TrajectoryContext,
  type TrajectoryStepForJudge,
} from './scoring'

// Storage infrastructure
export {
  type AccessCondition,
  type AccessControlPolicy,
  type AuthSignature,
  type CIDResponse,
  createStaticTrajectoryStorage,
  downloadTrajectoryBatch,
  type EncryptedPayload,
  type EncryptedTrajectory,
  EncryptedTrajectoryStorage,
  type EncryptionProvider,
  getEncryptedTrajectoryStorage,
  getStaticTrajectoryStorage,
  getStorage,
  getStorageProvider,
  type IPFSUploadResult,
  isCIDResponse,
  isEncryptedPayload,
  isIPFSUploadResult,
  isJsonRecord,
  type ModelMetadata,
  type PolicyCondition,
  resetEncryptedTrajectoryStorage,
  type SecretPolicy,
  type StaticStorageConfig,
  StaticTrajectoryStorage,
  type StorageConfig,
  type StorageOptions,
  StorageUtil,
  shouldUseStorage,
  shutdownAllStaticStorage,
  type TrajectoryBatch,
  type TrajectoryBatchReference,
} from './storage'

// TEE training workers
export {
  type BenchmarkResult as TEEBenchmarkResult,
  createTrainingWorker,
  type DataPrepResult,
  isArrayOf,
  isCIDResponse as isTEECIDResponse,
  isGenericObject,
  isJudgingScoreResponse,
  isScoredTrainingData,
  isSimulationResultResponse,
  isTEEInitResponse,
  isTEEProvider,
  isTrainingComputeResponse,
  type JudgingResult,
  type JudgingScoreResponse,
  type SimulationResultResponse,
  type TEEInitResponse,
  type TEEProvider,
  type TrainingComputeResponse,
  type TrainingResult as TEETrainingResult,
  TrainingWorker,
  type WorkerAttestation,
  type WorkerConfig,
  WorkerStatus,
  WorkerType,
} from './tee'
