export {
  createAdminConfig,
  createAdminConfigFromEnv,
  hasPermission,
  isSuperAdmin,
  requireAdmin,
  requireRole,
  validateAdmin,
} from './admin/core.js'
export {
  type AdminContext,
  type AdminPluginConfig,
  adminPlugin,
  requireAdminMiddleware,
  requireRoleMiddleware,
  withAdmin,
  withRole,
} from './admin/elysia.js'
export {
  type AdminConfig,
  ROLE_HIERARCHY,
} from './admin/types.js'
export {
  authenticate,
  type CombinedAuthConfig,
  constantTimeCompare,
  createWalletAuthMessage,
  extractAuthHeaders,
  parseWalletAuthMessage,
  requireAuth,
  validateAPIKey,
  validateAPIKeyFromHeaders,
  validateOAuth3FromHeaders,
  validateOAuth3Session,
  validateWalletSignature,
  validateWalletSignatureFromHeaders,
} from './auth/core.js'
export {
  type AuthContext,
  type AuthPluginConfig,
  apiKeyAuthPlugin,
  authErrorHandler,
  authPlugin,
  createAuthDerive,
  createAuthGuard,
  createElysiaAuth,
  oauth3AuthPlugin,
  requireAuthMiddleware,
  walletAuthPlugin,
  withAuth,
} from './auth/elysia.js'
export {
  AdminRole,
  type AdminUser,
  type AdminValidationResult,
  type APIKeyConfig,
  type APIKeyInfo,
  type APIKeyValidationResult,
  AuthError,
  AuthErrorCode,
  type AuthHeaders,
  AuthMethod,
  type AuthResult,
  type AuthUser,
  type OAuth3Config,
  type OAuth3ValidationResult,
  type WalletSignatureConfig,
  type WalletSignatureValidationResult,
} from './auth/types.js'
export {
  APIError,
  assert,
  ConflictError,
  createElysiaErrorHandler,
  type ErrorResponse,
  expectDefined,
  expectValid,
  ForbiddenError,
  getStatusCode,
  InternalError,
  NotFoundError,
  ServiceUnavailableError,
  sanitizeErrorMessage,
  toErrorResponse,
  UnauthorizedError,
  ValidationError,
} from './error-handler.js'
export {
  createRateLimitHeaders,
  createRateLimitKey,
  extractClientIp,
  getRateLimiter,
  InMemoryRateLimitStore,
  initRateLimiter,
  RateLimiter,
  resetRateLimiter,
} from './rate-limiting/core.js'
export {
  type RateLimitContext,
  type RateLimitPluginConfig,
  rateLimitPlugin,
  simpleRateLimit,
  tieredRateLimit,
  withRateLimit,
} from './rate-limiting/elysia.js'
export {
  type RateLimitEntry,
  type RateLimiterConfig,
  type RateLimitHeaders,
  type RateLimitResult,
  type RateLimitStore,
  type RateLimitTier,
  RateLimitTiers,
} from './rate-limiting/types.js'
