name: Example CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CI: true

jobs:
  lint:
    name: Lint
    runs-on: jeju-compute
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bun install

      - name: Run type check
        run: bun run tsc --noEmit

  test:
    name: Test
    runs-on: jeju-compute
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

  build:
    name: Build
    runs-on: jeju-compute
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7

